In [5]:
import pandas as pd

df = pd.read_csv("Airline Passengers.csv")

df["Month"] = pd.to_datetime(df["Month"])

df = df.set_index("Month")

df.head()

            Passengers
Month
1949-01-01         112
1949-02-01         118
1949-03-01         132
1949-04-01         129
1949-05-01         121

In [6]:
df.tail()

            Passengers
Month
1960-08-01         606
1960-09-01         508
1960-10-01         461
1960-11-01         390
1960-12-01         432

New information is based on previous information.